service: saas-image-extractor

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 2048
  timeout: 900         # 15-minute max
  environment:
    S3_BUCKET: ${self:service}-data
    FIRECRAWL_API_KEY: ${env:FIRECRAWL_API_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    DEPLOYMENT_VERSION: ${env:DEPLOYMENT_VERSION, 'v1.0.1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${self:service}-data/*
        - arn:aws:s3:::${self:service}-data

functions:
  extractor:
    handler: src/handlers/index.handler
    events:
      - http:
          path: extract
          method: post

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 1
              Status: Enabled
